# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completion_date',
            field=models.DateField(verbose_name='date completed'),
        ),
        migrations.AlterField(
            model_name='project',
            name='confirmation_date',
            field=models.DateField(verbose_name='confirmation date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_date',
            field=models.DateField(verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(verbose_name='due date'),
        ),
    ]
