# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20160609_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
