# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_auto_20160613_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
