# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_lineitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item', to='work.Project'),
        ),
    ]
