# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_auto_20160613_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
