# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_auto_20160613_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='city',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='state',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='street',
            field=models.TextField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='zip_code',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
