# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('QT', 'Quote'), ('WO', 'Word Order'), ('CO', 'Complete')], default='QT', max_length=2),
        ),
    ]
