# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0016_auto_20160616_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='is_service',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('QT', 'Quote'), ('WO', 'Work Order'), ('CO', 'Complete')], default='QT', max_length=2),
        ),
    ]
