# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0018_project_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
