# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0019_auto_20160619_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deposit',
            field=models.IntegerField(default=50.0),
        ),
    ]
