# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0020_auto_20160704_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineitem',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='lineitem',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
