# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0023_auto_20160811_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
    ]
