# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0025_auto_20160816_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
