# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0026_auto_20160816_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='name',
            field=models.CharField(choices=[('Strainer Bar', 'Strainer Bar'), ('Stretching Fee', 'Stretching Fee'), ('Pedestal', 'Pedestal'), ('Framing', 'Framing'), ('Crating', 'Crating'), ('Custom', 'Custom')], max_length=15),
        ),
    ]
