# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0027_auto_20160816_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='name',
            field=models.CharField(choices=[('Strainer Bar', 'Strainer Bar'), ('Stretching Fee', 'Stretching Fee'), ('Panel', 'Panel'), ('Pedestal', 'Pedestal'), ('Framing', 'Framing'), ('Crating', 'Crating'), ('Welding', 'Welding'), ('Custom', 'Custom')], max_length=15),
        ),
    ]
